// ── Custom type IDs for per-zone color selectors ──────────────────────────────
// ZeppOS reserves 0x186a0–UINT32_MAX for developer custom types.
const BASE = 0x186a0

// Sentinel used as default_type for color groups (= no override active).
// Not present in ALL_COLORS so getColorFromType returns null → theme color is used.
export const NO_OVERRIDE_TYPE = BASE + 0

// ── Named color constants ─────────────────────────────────────────────────────
// Use these in themes.js for readable references: COLOR.WARM_GOLD, COLOR.CORAL, …
export const COLOR = {
  // ── Curated override palette (IDs 1-12, shown in per-zone picker) ──────────
  WHITE:             BASE +  1,
  RED:               BASE +  2,
  ORANGE:            BASE +  3,
  YELLOW:            BASE +  4,
  GREEN:             BASE +  5,
  CYAN:              BASE +  6,
  SKY_BLUE:          BASE +  7,
  BLUE:              BASE +  8,
  PURPLE:            BASE +  9,
  PINK:              BASE + 10,
  GOLD:              BASE + 11,
  LIME:              BASE + 12,
  // ── Theme-specific colors (IDs 13+, not shown in picker) ───────────────────
  ORCHID:            BASE + 13,
  LIGHT_PINK:        BASE + 14,
  PLUM:              BASE + 15,
  VIVID_SKY:         BASE + 16,
  CORNFLOWER:        BASE + 17,
  INDIGO:            BASE + 18,
  DEEP_ORANGE:       BASE + 19,
  AMBER:             BASE + 20,
  LIGHT_AMBER:       BASE + 21,
  PEACH:             BASE + 22,
  MEDIUM_BLUE:       BASE + 23,
  GOLDEN_YELLOW:     BASE + 24,
  LIME_YELLOW:       BASE + 25,
  PERIWINKLE:        BASE + 26,
  HOT_PINK:          BASE + 27,
  PASTEL_PINK:       BASE + 28,
  BLUSH:             BASE + 29,
  MEADOW_GREEN:      BASE + 30,
  PURE_RED:          BASE + 31,
  PURE_BLUE:         BASE + 32,
  ROYAL_BLUE:        BASE + 33,
  PURE_YELLOW:       BASE + 34,
  LIGHT_SKY:         BASE + 35,
  AQUAMARINE:        BASE + 36,
  TURQUOISE:         BASE + 37,
  ELECTRIC_CYAN:     BASE + 38,
  NEON_SKY:          BASE + 39,
  TOMATO:            BASE + 40,
  ORANGE_RED:        BASE + 41,
  CORAL:             BASE + 42,
  EMERALD:           BASE + 43,
  FOREST_GREEN:      BASE + 44,
  SEA_GREEN:         BASE + 45,
  DARK_SEA_GREEN:    BASE + 46,
  HONEY:             BASE + 47,
  PALE_YELLOW:       BASE + 48,
  LIGHT_TURQUOISE:   BASE + 49,
  MEDIUM_TURQUOISE:  BASE + 50,
  MEDIUM_PINK:       BASE + 51,
  PALE_PINK:         BASE + 52,
  DARK_RED:          BASE + 53,
  DODGER_BLUE:       BASE + 54,
  MINT_GREEN:        BASE + 55,
  VIVID_ORANGE:      BASE + 56,
  SEA_TEAL:          BASE + 57,
  FUCHSIA:           BASE + 58,
  PURE_CYAN:         BASE + 59,
  VIOLET:            BASE + 60,
  LIGHT_AQUAMARINE:  BASE + 61,
  PURE_GREEN:        BASE + 62,
  CRIMSON:           BASE + 63,
  BRIGHT_GREEN:      BASE + 64,
  BLUE_VIOLET:       BASE + 65,
  MEDIUM_ORCHID:     BASE + 66,
  WARM_GOLD:         BASE + 67,
  MOCCASIN:          BASE + 68,
  OCEAN_BLUE:        BASE + 69,
  OCEAN_SKY:         BASE + 70,
  ICE_BLUE:          BASE + 71,
  PALE_SKY:          BASE + 72,
  DEEP_PINK:         BASE + 73,
  DARK_AMBER:        BASE + 74,
  CREAM:             BASE + 75,
  SALMON:            BASE + 76,
  LIGHT_SALMON:      BASE + 77,
  ICE_GRAY:          BASE + 78,
  BLUE_GRAY:         BASE + 79,
  SLATE:             BASE + 80,
  LIGHT_GRAY:        BASE + 81,
  NEON_GREEN:        BASE + 82,
  NEON_PINK:         BASE + 83,
  RUST:              BASE + 84,
  CINNABAR:          BASE + 85,
  AMBER_ORANGE:      BASE + 86,
  PASTEL_ORANGE:     BASE + 87,
  NEON_TEAL:         BASE + 88,
  LAVENDER:          BASE + 89,
  PASTEL_BLUE:       BASE + 90,
  MINT:              BASE + 91,
  RUBY:              BASE + 92,
  BURGUNDY:          BASE + 93,
  LEMON:             BASE + 94,
  ANTIQUE_GOLD:      BASE + 95,
  AMETHYST:          BASE + 96,
  LIGHT_LAVENDER:    BASE + 97,
  PALE_LAVENDER:     BASE + 98,
  LIGHT_AMETHYST:    BASE + 99,
  BANANA:            BASE + 100,
  TROPICAL_BLUE:     BASE + 101,
  TROPICAL_PINK:     BASE + 102,
  SILVER:            BASE + 103,
  PALE_BLUE:         BASE + 104,
  PALE_CYAN:         BASE + 105,
}

// ── Full color palette ────────────────────────────────────────────────────────
export const ALL_COLORS = [
  // ── Curated override palette ─────────────────────────────────────────────
  { id:  1, type: COLOR.WHITE,             color: 0xffffff, name: 'White'            },
  { id:  2, type: COLOR.RED,               color: 0xff3b3b, name: 'Red'              },
  { id:  3, type: COLOR.ORANGE,            color: 0xff8c00, name: 'Orange'           },
  { id:  4, type: COLOR.YELLOW,            color: 0xffeb3b, name: 'Yellow'           },
  { id:  5, type: COLOR.GREEN,             color: 0x8bc34a, name: 'Green'            },
  { id:  6, type: COLOR.CYAN,              color: 0x00bcd4, name: 'Cyan'             },
  { id:  7, type: COLOR.SKY_BLUE,          color: 0x29b6f6, name: 'Sky Blue'         },
  { id:  8, type: COLOR.BLUE,              color: 0x3f51b5, name: 'Blue'             },
  { id:  9, type: COLOR.PURPLE,            color: 0x9c27b0, name: 'Purple'           },
  { id: 10, type: COLOR.PINK,              color: 0xe91e63, name: 'Pink'             },
  { id: 11, type: COLOR.GOLD,              color: 0xffd700, name: 'Gold'             },
  { id: 12, type: COLOR.LIME,              color: 0x00e676, name: 'Lime'             },
  // ── Theme-specific colors ────────────────────────────────────────────────
  { id: 13, type: COLOR.ORCHID,            color: 0xc658fb, name: 'Orchid'           },
  { id: 14, type: COLOR.LIGHT_PINK,        color: 0xff78b7, name: 'Light Pink'       },
  { id: 15, type: COLOR.PLUM,              color: 0xdda0dd, name: 'Plum'             },
  { id: 16, type: COLOR.VIVID_SKY,         color: 0x03a9f4, name: 'Vivid Sky'        },
  { id: 17, type: COLOR.CORNFLOWER,        color: 0x2196f3, name: 'Cornflower'       },
  { id: 18, type: COLOR.INDIGO,            color: 0x673ab7, name: 'Indigo'           },
  { id: 19, type: COLOR.DEEP_ORANGE,       color: 0xff5722, name: 'Deep Orange'      },
  { id: 20, type: COLOR.AMBER,             color: 0xff9800, name: 'Amber'            },
  { id: 21, type: COLOR.LIGHT_AMBER,       color: 0xffc107, name: 'Light Amber'      },
  { id: 22, type: COLOR.PEACH,             color: 0xffe0b2, name: 'Peach'            },
  { id: 23, type: COLOR.MEDIUM_BLUE,       color: 0x3182de, name: 'Medium Blue'      },
  { id: 24, type: COLOR.GOLDEN_YELLOW,     color: 0xffcc33, name: 'Golden Yellow'    },
  { id: 25, type: COLOR.LIME_YELLOW,       color: 0xe4fa3c, name: 'Lime Yellow'      },
  { id: 26, type: COLOR.PERIWINKLE,        color: 0x8080ff, name: 'Periwinkle'       },
  { id: 27, type: COLOR.HOT_PINK,          color: 0xff4081, name: 'Hot Pink'         },
  { id: 28, type: COLOR.PASTEL_PINK,       color: 0xff80ab, name: 'Pastel Pink'      },
  { id: 29, type: COLOR.BLUSH,             color: 0xffcdd2, name: 'Blush'            },
  { id: 30, type: COLOR.MEADOW_GREEN,      color: 0x4caf50, name: 'Meadow Green'     },
  { id: 31, type: COLOR.PURE_RED,          color: 0xff0000, name: 'Pure Red'         },
  { id: 32, type: COLOR.PURE_BLUE,         color: 0x0000ff, name: 'Pure Blue'        },
  { id: 33, type: COLOR.ROYAL_BLUE,        color: 0x4169e1, name: 'Royal Blue'       },
  { id: 34, type: COLOR.PURE_YELLOW,       color: 0xffff00, name: 'Pure Yellow'      },
  { id: 35, type: COLOR.LIGHT_SKY,         color: 0x87ceeb, name: 'Light Sky'        },
  { id: 36, type: COLOR.AQUAMARINE,        color: 0x64ffda, name: 'Aquamarine'       },
  { id: 37, type: COLOR.TURQUOISE,         color: 0x00bfa5, name: 'Turquoise'        },
  { id: 38, type: COLOR.ELECTRIC_CYAN,     color: 0x18ffff, name: 'Electric Cyan'    },
  { id: 39, type: COLOR.NEON_SKY,          color: 0x00e5ff, name: 'Neon Sky'         },
  { id: 40, type: COLOR.TOMATO,            color: 0xff6347, name: 'Tomato'           },
  { id: 41, type: COLOR.ORANGE_RED,        color: 0xff4500, name: 'Orange Red'       },
  { id: 42, type: COLOR.CORAL,             color: 0xff7f50, name: 'Coral'            },
  { id: 43, type: COLOR.EMERALD,           color: 0x2ecc71, name: 'Emerald'          },
  { id: 44, type: COLOR.FOREST_GREEN,      color: 0x27ae60, name: 'Forest Green'     },
  { id: 45, type: COLOR.SEA_GREEN,         color: 0x1abc9c, name: 'Sea Green'        },
  { id: 46, type: COLOR.DARK_SEA_GREEN,    color: 0x16a085, name: 'Dark Sea Green'   },
  { id: 47, type: COLOR.HONEY,             color: 0xffd54f, name: 'Honey'            },
  { id: 48, type: COLOR.PALE_YELLOW,       color: 0xfff176, name: 'Pale Yellow'      },
  { id: 49, type: COLOR.LIGHT_TURQUOISE,   color: 0x48c9b0, name: 'Light Turquoise'  },
  { id: 50, type: COLOR.MEDIUM_TURQUOISE,  color: 0x45b39d, name: 'Medium Turquoise' },
  { id: 51, type: COLOR.MEDIUM_PINK,       color: 0xf06292, name: 'Medium Pink'      },
  { id: 52, type: COLOR.PALE_PINK,         color: 0xf8bbd0, name: 'Pale Pink'        },
  { id: 53, type: COLOR.DARK_RED,          color: 0x8b0000, name: 'Dark Red'         },
  { id: 54, type: COLOR.DODGER_BLUE,       color: 0x1e90ff, name: 'Dodger Blue'      },
  { id: 55, type: COLOR.MINT_GREEN,        color: 0x98ff98, name: 'Mint Green'       },
  { id: 56, type: COLOR.VIVID_ORANGE,      color: 0xffa500, name: 'Vivid Orange'     },
  { id: 57, type: COLOR.SEA_TEAL,          color: 0x20b2aa, name: 'Sea Teal'         },
  { id: 58, type: COLOR.FUCHSIA,           color: 0xff00ff, name: 'Fuchsia'          },
  { id: 59, type: COLOR.PURE_CYAN,         color: 0x00ffff, name: 'Pure Cyan'        },
  { id: 60, type: COLOR.VIOLET,            color: 0xee82ee, name: 'Violet'           },
  { id: 61, type: COLOR.LIGHT_AQUAMARINE,  color: 0x7fffd4, name: 'Light Aquamarine' },
  { id: 62, type: COLOR.PURE_GREEN,        color: 0x00ff00, name: 'Pure Green'       },
  { id: 63, type: COLOR.CRIMSON,           color: 0xdc143c, name: 'Crimson'          },
  { id: 64, type: COLOR.BRIGHT_GREEN,      color: 0x32cd32, name: 'Bright Green'     },
  { id: 65, type: COLOR.BLUE_VIOLET,       color: 0x8a2be2, name: 'Blue Violet'      },
  { id: 66, type: COLOR.MEDIUM_ORCHID,     color: 0xba55d3, name: 'Medium Orchid'    },
  { id: 67, type: COLOR.WARM_GOLD,         color: 0xffb347, name: 'Warm Gold'        },
  { id: 68, type: COLOR.MOCCASIN,          color: 0xffe4b5, name: 'Moccasin'         },
  { id: 69, type: COLOR.OCEAN_BLUE,        color: 0x0096c7, name: 'Ocean Blue'       },
  { id: 70, type: COLOR.OCEAN_SKY,         color: 0x48cae4, name: 'Ocean Sky'        },
  { id: 71, type: COLOR.ICE_BLUE,          color: 0x90e0ef, name: 'Ice Blue'         },
  { id: 72, type: COLOR.PALE_SKY,          color: 0xade8f4, name: 'Pale Sky'         },
  { id: 73, type: COLOR.DEEP_PINK,         color: 0xc2185b, name: 'Deep Pink'        },
  { id: 74, type: COLOR.DARK_AMBER,        color: 0xff8f00, name: 'Dark Amber'       },
  { id: 75, type: COLOR.CREAM,             color: 0xfff9c4, name: 'Cream'            },
  { id: 76, type: COLOR.SALMON,            color: 0xff6b6b, name: 'Salmon'           },
  { id: 77, type: COLOR.LIGHT_SALMON,      color: 0xffa07a, name: 'Light Salmon'     },
  { id: 78, type: COLOR.ICE_GRAY,          color: 0xcfd8dc, name: 'Ice Gray'         },
  { id: 79, type: COLOR.BLUE_GRAY,         color: 0x90a4ae, name: 'Blue Gray'        },
  { id: 80, type: COLOR.SLATE,             color: 0x78909c, name: 'Slate'            },
  { id: 81, type: COLOR.LIGHT_GRAY,        color: 0xb0bec5, name: 'Light Gray'       },
  { id: 82, type: COLOR.NEON_GREEN,        color: 0x39ff14, name: 'Neon Green'       },
  { id: 83, type: COLOR.NEON_PINK,         color: 0xff1493, name: 'Neon Pink'        },
  { id: 84, type: COLOR.RUST,              color: 0xd35400, name: 'Rust'             },
  { id: 85, type: COLOR.CINNABAR,          color: 0xe74c3c, name: 'Cinnabar'         },
  { id: 86, type: COLOR.AMBER_ORANGE,      color: 0xf39c12, name: 'Amber Orange'     },
  { id: 87, type: COLOR.PASTEL_ORANGE,     color: 0xf8c471, name: 'Pastel Orange'    },
  { id: 88, type: COLOR.NEON_TEAL,         color: 0x00cec9, name: 'Neon Teal'        },
  { id: 89, type: COLOR.LAVENDER,          color: 0xa29bfe, name: 'Lavender'         },
  { id: 90, type: COLOR.PASTEL_BLUE,       color: 0x74b9ff, name: 'Pastel Blue'      },
  { id: 91, type: COLOR.MINT,              color: 0x55efc4, name: 'Mint'             },
  { id: 92, type: COLOR.RUBY,              color: 0xc0392b, name: 'Ruby'             },
  { id: 93, type: COLOR.BURGUNDY,          color: 0x922b21, name: 'Burgundy'         },
  { id: 94, type: COLOR.LEMON,             color: 0xf1c40f, name: 'Lemon'            },
  { id: 95, type: COLOR.ANTIQUE_GOLD,      color: 0xe8c44d, name: 'Antique Gold'     },
  { id: 96, type: COLOR.AMETHYST,          color: 0x9b59b6, name: 'Amethyst'         },
  { id: 97, type: COLOR.LIGHT_LAVENDER,    color: 0xc39bd3, name: 'Light Lavender'   },
  { id: 98, type: COLOR.PALE_LAVENDER,     color: 0xd7bde2, name: 'Pale Lavender'    },
  { id: 99, type: COLOR.LIGHT_AMETHYST,    color: 0xab8bc8, name: 'Light Amethyst'   },
  { id: 100, type: COLOR.BANANA,           color: 0xfeca57, name: 'Banana'           },
  { id: 101, type: COLOR.TROPICAL_BLUE,    color: 0x48dbfb, name: 'Tropical Blue'    },
  { id: 102, type: COLOR.TROPICAL_PINK,    color: 0xff9ff3, name: 'Tropical Pink'    },
  { id: 103, type: COLOR.SILVER,           color: 0xbdc3c7, name: 'Silver'           },
  { id: 104, type: COLOR.PALE_BLUE,        color: 0x90caf9, name: 'Pale Blue'        },
  { id: 105, type: COLOR.PALE_CYAN,        color: 0xb2ebf2, name: 'Pale Cyan'        },
]

// Curated palette subset (IDs 1-12) — kept for reference/filtering
export const COLOR_ENTRIES = ALL_COLORS.filter(c => c.id <= 12)

// optional_types array for WATCHFACE_EDIT_GROUP
// First entry is the "use theme color" sentinel (NO_OVERRIDE_TYPE), then all 105 colors.
export const colorOptionalArray = [
  { type: NO_OVERRIDE_TYPE, preview: 'preview/step.png', title_en: 'Theme', title_sc: 'Tema', title_tc: 'Tema' },
  ...ALL_COLORS.map(c => ({
    type:     c.type,
    preview:  'bg/color/prev_' + c.id + '.png',
    title_en: c.name,
    title_sc: c.name,
    title_tc: c.name,
  }))
]

// Returns the hex color for a given type ID.
// Returns null for NO_OVERRIDE_TYPE or any unknown type (= no override, use theme color).
export function getColorFromType(typeId) {
  const entry = ALL_COLORS.find(c => c.type === typeId)
  return entry ? entry.color : null
}

// optional_types for the HOUR color group — preview shows "undici" in each color
export const hourColorOptionalArray = [
  { type: NO_OVERRIDE_TYPE, preview: 'bg/color/hour_prev_0.png', title_en: 'Theme', title_sc: 'Tema', title_tc: 'Tema' },
  ...ALL_COLORS.map(c => ({
    type:     c.type,
    preview:  'bg/color/hour_prev_' + c.id + '.png',
    title_en: c.name,
    title_sc: c.name,
    title_tc: c.name,
  }))
]

// edit_id values for the 3 color selector groups (must not clash with 101/110/111/112)
export const COLOR_EDIT_ID = {
  HOUR:   120,
  MINUTE: 121,
  DATE:   122,
}
